spring:
  profiles:
    default: local

  # data.sql 파일 실행 위해 임의로 추가
  sql:
    init:
      mode: always
  # data.sql 파일 실행 위해 임의로 추가

  datasource:
#    url: jdbc:h2:mem:~/cafeKioskApplication
    url: jdbc:h2:tcp://localhost/~/cafeKioskApplication
    driver-class-name: org.h2.Driver
    username: sa
    password:

    # data.sql 파일 실행 위해 임의로 추가
    data: classpath:data.sql
    initialization-mode: always
    # data.sql 파일 실행 위해 임의로 추가

  jpa:
    hibernate:
      ddl-auto: create

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true # (2.5~) Hibernate 초기화 이후 data.sql 실행


  h2:
    console:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
